<a href="https://colab.research.google.com/github/Ritik-code10/pandas-/blob/main/classpractical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/matches.csv")

In [ ]:
df.head()

,id,Season,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,new_id
0,1,IPL-2017,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1792.178571
1,2,IPL-2017,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,1792.178571
2,3,IPL-2017,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,1792.178571
3,4,IPL-2017,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,1792.178571
4,5,IPL-2017,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,1792.178571

In [ ]:
df.sample

<bound method NDFrame.sample of         id    Season           city        date                        team1  \
0        1  IPL-2017      Hyderabad  05-04-2017          Sunrisers Hyderabad
1        2  IPL-2017           Pune  06-04-2017               Mumbai Indians
2        3  IPL-2017         Rajkot  07-04-2017                Gujarat Lions
3        4  IPL-2017         Indore  08-04-2017       Rising Pune Supergiant
4        5  IPL-2017      Bangalore  08-04-2017  Royal Challengers Bangalore
..     ...       ...            ...         ...                          ...
751  11347  IPL-2019         Mumbai  05-05-2019        Kolkata Knight Riders
752  11412  IPL-2019        Chennai  07-05-2019          Chennai Super Kings
753  11413  IPL-2019  Visakhapatnam  08-05-2019          Sunrisers Hyderabad
754  11414  IPL-2019  Visakhapatnam  10-05-2019               Delhi Capitals
755  11415  IPL-2019      Hyderabad  12-05-2019               Mumbai Indians

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
751               Mumbai Indians               Mumbai Indians         field
752               Mumbai Indians          Chennai Super Kings           bat
753               Delhi Capitals               Delhi Capitals         field
754          Chennai Super Kings          Chennai Super Kings         field
755          Chennai Super Kings               Mumbai Indians           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
751  normal           0               Mumbai Indians            0
752  normal           0               Mumbai Indians            0
753  normal           0               Delhi Capitals            0
754  normal           0          Chennai Super Kings            0
755  normal           0               Mumbai Indians            1

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
751               9       HH Pandya
752               6        AS Yadav
753               2         RR Pant
754               6    F du Plessis
755               0       JJ Bumrah

                                         venue         umpire1  \
0    Rajiv Gandhi International Stadium, Uppal     AY Dandekar
1      Maharashtra Cricket Association Stadium  A Nand Kishore
2       Saurashtra Cricket Association Stadium     Nitin Menon
3                       Holkar Cricket Stadium    AK Chaudhary
4                        M Chinnaswamy Stadium             NaN
..                                         ...             ...
751                           Wankhede Stadium   Nanda Kishore
752                  M. A. Chidambaram Stadium     Nigel Llong
753                           ACA-VDCA Stadium             NaN
754                           ACA-VDCA Stadium   Sundaram Ravi
755         Rajiv Gandhi Intl. Cricket Stadium     Nitin Menon

            umpire2                  umpire3
0          NJ Llong                      NaN
1            S Ravi                      NaN
2         CK Nandan                      NaN
3     C Shamshuddin                      NaN
4               NaN                      NaN
..              ...                      ...
751        O Nandan                   S Ravi
752     Nitin Menon                Ian Gould
753             NaN                      NaN
754  Bruce Oxenford  Chettithody Shamshuddin
755       Ian Gould              Nigel Llong

[756 rows x 18 columns]>

In [ ]:
df.tail()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [ ]:
df.info

<bound method DataFrame.info of         id    Season           city        date                        team1  \
0        1  IPL-2017      Hyderabad  05-04-2017          Sunrisers Hyderabad
1        2  IPL-2017           Pune  06-04-2017               Mumbai Indians
2        3  IPL-2017         Rajkot  07-04-2017                Gujarat Lions
3        4  IPL-2017         Indore  08-04-2017       Rising Pune Supergiant
4        5  IPL-2017      Bangalore  08-04-2017  Royal Challengers Bangalore
..     ...       ...            ...         ...                          ...
751  11347  IPL-2019         Mumbai  05-05-2019        Kolkata Knight Riders
752  11412  IPL-2019        Chennai  07-05-2019          Chennai Super Kings
753  11413  IPL-2019  Visakhapatnam  08-05-2019          Sunrisers Hyderabad
754  11414  IPL-2019  Visakhapatnam  10-05-2019               Delhi Capitals
755  11415  IPL-2019      Hyderabad  12-05-2019               Mumbai Indians

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
751               Mumbai Indians               Mumbai Indians         field
752               Mumbai Indians          Chennai Super Kings           bat
753               Delhi Capitals               Delhi Capitals         field
754          Chennai Super Kings          Chennai Super Kings         field
755          Chennai Super Kings               Mumbai Indians           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
751  normal           0               Mumbai Indians            0
752  normal           0               Mumbai Indians            0
753  normal           0               Delhi Capitals            0
754  normal           0          Chennai Super Kings            0
755  normal           0               Mumbai Indians            1

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
751               9       HH Pandya
752               6        AS Yadav
753               2         RR Pant
754               6    F du Plessis
755               0       JJ Bumrah

                                         venue         umpire1  \
0    Rajiv Gandhi International Stadium, Uppal     AY Dandekar
1      Maharashtra Cricket Association Stadium  A Nand Kishore
2       Saurashtra Cricket Association Stadium     Nitin Menon
3                       Holkar Cricket Stadium    AK Chaudhary
4                        M Chinnaswamy Stadium             NaN
..                                         ...             ...
751                           Wankhede Stadium   Nanda Kishore
752                  M. A. Chidambaram Stadium     Nigel Llong
753                           ACA-VDCA Stadium             NaN
754                           ACA-VDCA Stadium   Sundaram Ravi
755         Rajiv Gandhi Intl. Cricket Stadium     Nitin Menon

            umpire2                  umpire3
0          NJ Llong                      NaN
1            S Ravi                      NaN
2         CK Nandan                      NaN
3     C Shamshuddin                      NaN
4               NaN                      NaN
..              ...                      ...
751        O Nandan                   S Ravi
752     Nitin Menon                Ian Gould
753             NaN                      NaN
754  Bruce Oxenford  Chettithody Shamshuddin
755       Ian Gould              Nigel Llong

[756 rows x 18 columns]>

In [ ]:
df.describe()

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

In [ ]:
df.shape

(756, 18)

In [ ]:
df.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=756, step=1)

In [ ]:
df.dtypes

id                  int64
Season             object
city               object
date               object
team1              object
team2              object
toss_winner        object
toss_decision      object
result             object
dl_applied          int64
winner             object
win_by_runs         int64
win_by_wickets      int64
player_of_match    object
venue              object
umpire1            object
umpire2            object
umpire3            object
dtype: object

In [ ]:
df.loc[0,'city']

'Hyderabad'

In [ ]:
df.iloc[0,0]

np.int64(1)

In [ ]:
df['new_id']  = df['id'].mean()

In [ ]:
df['new_city'] =df['city']+df['team1']

In [ ]:
df.drop(columns=["city",'new_city'], inplace=True)

In [ ]:
df.groupby('team1')['team2'].count()

team1
Chennai Super Kings             89
Deccan Chargers                 43
Delhi Capitals                   6
Delhi Daredevils                72
Gujarat Lions                   14
Kings XI Punjab                 91
Kochi Tuskers Kerala             7
Kolkata Knight Riders           83
Mumbai Indians                 101
Pune Warriors                   20
Rajasthan Royals                67
Rising Pune Supergiant           8
Rising Pune Supergiants          7
Royal Challengers Bangalore     85
Sunrisers Hyderabad             63
Name: team2, dtype: int64

In [ ]:
import pandas as pd
df = pd.DataFrame({

'Name' : ['Alice Johnson', 'BOB SMITH', 'carol white'],

'Email' : ['alice@gmail.com', 'bob@yahoo.com','carol@outlook.com'],

'Phone': ['9876543210', '98-7654-3210', '+91-9876543210'],

'Address':['221B Baker Street, London, UK', '1600 Penn Ave, Washington, USA', '10 Downing St, London, UK']

})

In [ ]:
df['Name_Clean'] = df['Name'].str.strip().str.title()
df['Email_Lower'] = df['Name'].str.lower()
df['Name_Clean']

0    Alice Johnson
1        Bob Smith
2      Carol White
Name: Name_Clean, dtype: object

In [ ]:
df['Is_Gmail'] = df['Email'].str.contains('@gmail.com')
df['starts_A'] = df['Name_Clean'].str.startswith('A')
df['Is_Gmail']
df['starts_A']

0     True
1    False
2    False
Name: starts_A, dtype: bool

In [ ]:
df['Domain'] = df['Name_Clean']