<a href="https://colab.research.google.com/github/Ritik-code10/pandas-/blob/main/Data_Cleaning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning Assignment (Pandas)

Dataset: **movies_dataset.csv**

Complete all questions using Pandas.

## Q1. Import pandas and load the dataset.

In [37]:
import pandas as pd
df =pd.read_csv('/content/movies_dataset.csv')
df

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
0,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
1,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
2,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
3,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
4,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
301,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
302,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
303,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
304,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released

## Q2. Display first 10 rows.

In [38]:
df.head(10)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
0,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
1,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
2,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
3,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
4,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released
5,6,RRR,Scifi,2021,9.8,97 min,Director 17,NaN,English,$76M,"263,811",Disney+ Hotstar,PG-13,20-02-2023,Upcoming
6,7,Moana,Action,2023,8.3,148 min,Director 25,Japan,NaN,$170M,"564,003",Disney+ Hotstar,A,17-03-2024,Released
7,8,Pushpa,Sci-Fi,2019,5.8,179 min,Director 17,India,Spanish,$29M,"471,899",Amazon Prime,U/A,02-04-2024,Released
8,9,Titanic,Acton,2024,8.2,150 min,Director 6,Japan,Spanish,$236M,"652,773",Disney+ Hotstar,U/A,23-05-2023,Upcoming
9,10,Moana,Sci-Fi,2019,NaN,82 min,Director 19,Canada,Spanish,$56M,"160,234",Netflix,U,28-06-2020,Released

## Q3. Display last 10 rows.

In [39]:
df.tail(10)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
295,296,Avatar,Comedy,2021,NaN,134 min,Director 13,UK,NaN,$248M,"419,340",Netflix,U,25-08-2024,Released
296,297,Titanic,Animation,2018,8.3,170 min,Director 25,NaN,HINDI,$134M,"731,264",Amazon Prime,PG-13,06-12-2025,Upcoming
297,298,KGF,Animation,2018,7.2,101 min,Director 10,india,Spanish,$280M,"937,731",Netflix,A,18-11-2020,Upcoming
298,299,Moana,Scifi,2019,9.7,129 min,Director 3,india,Hindi,$240M,"545,580",Amazon Prime,U/A,06-11-2025,Released
299,300,Joker,Horror,2022,7.1,119 min,Director 13,USA,Spanish,$214M,"760,676",Netflix,U,07-03-2024,Released
300,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
301,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
302,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
303,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
304,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released

## Q4. Print shape.

In [40]:
df.shape

(305, 15)

## Q5. Print column names.

In [41]:
print(df.columns)

Index(['Movie_ID', 'Title', 'Genre', 'Release_Year', 'Rating', 'Duration',
       'Director', 'Country', 'Language', 'Budget', 'Revenue', 'Platform',
       'Age_Rating', 'Added_Date', 'Status'],
      dtype='object')

## Q6. Use info().

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie_ID      305 non-null    int64
 1   Title         282 non-null    object
 2   Genre         305 non-null    object
 3   Release_Year  305 non-null    int64
 4   Rating        278 non-null    float64
 5   Duration      305 non-null    object
 6   Director      305 non-null    object
 7   Country       272 non-null    object
 8   Language      240 non-null    object
 9   Budget        270 non-null    object
 10  Revenue       282 non-null    object
 11  Platform      305 non-null    object
 12  Age_Rating    305 non-null    object
 13  Added_Date    305 non-null    object
 14  Status        305 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 35.9+ KB

## Q7. Use describe().

In [43]:
df.describe()

         Movie_ID  Release_Year      Rating
count  305.000000    305.000000  278.000000
mean   148.081967   2021.108197    7.466547
std     88.052447      2.002818    1.321495
min      1.000000   2018.000000    5.000000
25%     72.000000   2019.000000    6.500000
50%    148.000000   2021.000000    7.500000
75%    224.000000   2023.000000    8.500000
max    300.000000   2024.000000    9.800000

## Q8. Find missing values.

In [44]:
df.isnull().sum()

Movie_ID         0
Title           23
Genre            0
Release_Year     0
Rating          27
Duration         0
Director         0
Country         33
Language        65
Budget          35
Revenue         23
Platform         0
Age_Rating       0
Added_Date       0
Status           0
dtype: int64

## Q9. Check duplicate rows.

In [45]:
df.duplicated().sum()

np.int64(5)

## Q10. Remove duplicate rows.

In [46]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

## Q11. Remove extra spaces from Title.

In [47]:
df['Title'] = df['Title'].str.strip()
df['Title']

0             NaN
1      The Batman
2           Jawan
3           Moana
4             KGF
          ...
295        Avatar
296       Titanic
297           KGF
298         Moana
299         Joker
Name: Title, Length: 300, dtype: object

## Q12. Convert Title to Proper Case.

In [48]:
df['Title'] = df['Title'].str.title()
df['Title']

0             NaN
1      The Batman
2           Jawan
3           Moana
4             Kgf
          ...
295        Avatar
296       Titanic
297           Kgf
298         Moana
299         Joker
Name: Title, Length: 300, dtype: object

## Q13. Correct Genre spellings (Acton→Action, Scifi→Sci-Fi, Romnce→Romance).

In [49]:
df['Genre'] = df['Genre'].replace({"Acton" : "Action" , "Scifi" : "Sci-Fi" , "Romnce" : "Romance"})
df['Genre']

0        Romance
1         Action
2         Action
3         Horror
4         Sci-Fi
         ...
295       Comedy
296    Animation
297    Animation
298       Sci-Fi
299       Horror
Name: Genre, Length: 300, dtype: object

## Q14. Convert Country to upper case.

In [50]:
df['Country'] = df['Country'].str.upper()
df['Country']

0         USA
1          UK
2      CANADA
3         USA
4       JAPAN
        ...
295        UK
296       NaN
297     INDIA
298     INDIA
299       USA
Name: Country, Length: 300, dtype: object

## Q15. Convert Language to lower case.

In [51]:
df['Language'] = df['Language'].str.lower()
df['Language']

0      spanish
1        hindi
2          NaN
3      spanish
4      english
        ...
295        NaN
296      hindi
297    spanish
298      hindi
299    spanish
Name: Language, Length: 300, dtype: object

## Q16. Convert Rating to float.

In [52]:
df['Rating'] = df['Rating'].astype(float)
df['Rating']

0      8.5
1      8.4
2      8.0
3      6.3
4      NaN
      ...
295    NaN
296    8.3
297    7.2
298    9.7
299    7.1
Name: Rating, Length: 300, dtype: float64

## Q17. Remove 'min' from Duration and convert to integer.

In [53]:
df['Duration'] = df['Duration'].str.replace('min','').astype(int)
df['Duration']

0      166
1      123
2      126
3      167
4      120
      ...
295    134
296    170
297    101
298    129
299    119
Name: Duration, Length: 300, dtype: int64

## Q18. Remove '$' and 'M' from Budget.

In [54]:
df['Budget'] = df['Budget'].str.replace('$','').str.replace('M','').astype(float)
df['Budget']

0       35.0
1      192.0
2        NaN
3      293.0
4      181.0
       ...
295    248.0
296    134.0
297    280.0
298    240.0
299    214.0
Name: Budget, Length: 300, dtype: float64

## Q19. Remove commas from Revenue and convert numeric.

In [55]:
df['Revenue'] = df['Revenue'].str.replace(',','').astype(float)
df['Revenue']

0      338517.0
1      489099.0
2      891296.0
3      267473.0
4      611405.0
         ...
295    419340.0
296    731264.0
297    937731.0
298    545580.0
299    760676.0
Name: Revenue, Length: 300, dtype: float64

## Q20. Convert Release_Year to integer.

In [56]:
df['Release_Year'] = df['Release_Year'].astype(int)
df['Release_Year']

0      2019
1      2024
2      2020
3      2020
4      2024
       ...
295    2021
296    2018
297    2018
298    2019
299    2022
Name: Release_Year, Length: 300, dtype: int64

## Q21. Convert Added_Date to datetime.

In [57]:
df['Added_Date'] = pd.to_datetime(df['Added_Date'])
df['Added_Date']

/tmp/ipykernel_743/3793245641.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Added_Date'] = pd.to_datetime(df['Added_Date'])

0     2025-04-18
1     2020-05-20
2     2023-02-28
3     2024-12-21
4     2021-05-05
         ...
295   2024-08-25
296   2025-12-06
297   2020-11-18
298   2025-11-06
299   2024-03-07
Name: Added_Date, Length: 300, dtype: datetime64[ns]

## Q22. Delete rows where Title is missing.

In [58]:
df.dropna(subset=['Title'], inplace=True)
df['Title']

1      The Batman
2           Jawan
3           Moana
4             Kgf
5             Rrr
          ...
295        Avatar
296       Titanic
297           Kgf
298         Moana
299         Joker
Name: Title, Length: 278, dtype: object

## Q23. Fill missing Rating with mean.

In [59]:
df['Rating'].fillna(df['Rating'].mean(),inplace=True)
df['Rating']

/tmp/ipykernel_743/1757335023.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].mean(),inplace=True)

1      8.400000
2      8.000000
3      6.300000
4      7.440392
5      9.800000
         ...
295    7.440392
296    8.300000
297    7.200000
298    9.700000
299    7.100000
Name: Rating, Length: 278, dtype: float64

## Q24. Fill missing Country with mode.

In [66]:
df['Country'].fillna(df['Country'].mode()[0],inplace=True)
df['Country']

#Language
df['Language'].fillna(df['Language'].mode()[0],inplace=True)
df['Language']

/tmp/ipykernel_743/2767188477.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Language'].fillna(df['Language'].mode()[0],inplace=True)

1        hindi
2        hindi
3      spanish
4      english
5      english
        ...
295      hindi
296      hindi
297    spanish
298      hindi
299    spanish
Name: Language, Length: 278, dtype: object

## Q25. Fill missing Budget with median.

In [68]:
df['Budget'].fillna(df['Budget'].median(),inplace=True)
df['Budget']

#Revenue
df['Revenue'].fillna(df['Revenue'].median(),inplace=True)
df['Revenue']

/tmp/ipykernel_743/1983659383.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Revenue'].fillna(df['Revenue'].median(),inplace=True)

1      489099.0
2      891296.0
3      267473.0
4      611405.0
5      263811.0
         ...
295    419340.0
296    731264.0
297    937731.0
298    545580.0
299    760676.0
Name: Revenue, Length: 278, dtype: float64

## Q26. Check if any null values remain.

In [69]:
df.isnull().sum()

Movie_ID        0
Title           0
Genre           0
Release_Year    0
Rating          0
Duration        0
Director        0
Country         0
Language        0
Budget          0
Revenue         0
Platform        0
Age_Rating      0
Added_Date      0
Status          0
dtype: int64

## Q27. Save cleaned dataset as clean_movies_dataset.csv.

In [70]:
save_df = df.to_csv('clean_movies_dataset.csv',index=False)

## Q28. Print Top 5 highest rated movies.

In [71]:
print(df.nlargest(5,'Rating'))

     Movie_ID    Title   Genre  Release_Year  Rating  Duration     Director  \
5           6      Rrr  Sci-Fi          2021     9.8        97  Director 17
53         54      Kgf   Drama          2024     9.7       147  Director 17
81         82  Titanic  Action          2022     9.7       150   Director 1
105       106   Pushpa  Sci-Fi          2022     9.7       116  Director 15
298       299    Moana  Sci-Fi          2019     9.7       129   Director 3

    Country Language  Budget   Revenue         Platform Age_Rating Added_Date  \
5     INDIA  english    76.0  263811.0  Disney+ Hotstar      PG-13 2023-02-20
53    JAPAN    hindi   266.0  402764.0     Amazon Prime          U 2021-02-15
81     USA     hindi   171.0  482259.0  Disney+ Hotstar          U 2022-02-12
105   INDIA    hindi   259.0  928115.0     Amazon Prime        U/A 2025-08-24
298   INDIA    hindi   240.0  545580.0     Amazon Prime        U/A 2025-11-06

       Status
5    Upcoming
53   Released
81   Released
105  Upcoming
298  Released

## Q29. Count movies platform-wise.

In [72]:
df.groupby('Platform')['Title'].count()

Platform
Amazon Prime        82
Disney+ Hotstar    100
Netflix             96
Name: Title, dtype: int64