<a href="https://colab.research.google.com/github/Ritik-code10/pandas-/blob/main/NumPy_Pandas_Project_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy + Pandas Assignment
## Beginner to Intermediate (Project Based)

**Instructions:**
- Solve all questions.
- Use the same dataset for all Pandas questions.
- Write your solution in the code cell below each question.

## Dataset

| EmpID | Name | Department | Salary | Age |
|------:|------|------------|-------:|----:|
|101|Raj|IT|50000|24|
|102|Amit|HR|42000|28|
|103|Neha|IT|65000|26|
|104|Priya|Finance|58000|30|
|105|Rohan|HR|45000|25|

## Question 1

Create a NumPy array using the salary values:

Input:
```
[50000,42000,65000,58000,45000]
```

Output:
```
array([50000,42000,65000,58000,45000])
```

In [ ]:
# Write your code here
import numpy as np
import pandas as pd

arr = np.array([50000,42000,65000,58000,45000])
arr

array([50000, 42000, 65000, 58000, 45000])

## Question 2

Using the NumPy array, find Total Salary, Average Salary and Maximum Salary.

Output:
```
Total Salary = 260000
Average Salary = 52000.0
Maximum Salary = 65000
```

In [ ]:
# Write your code here
print(f"Total Salary = {arr.sum()}")
print(f"AVerage Salary = {arr.mean()}")
print(f"Maximum Salary = {arr.max()}")

Total Salary = 260000
AVerage Salary = 52000.0
Maximum Salary = 65000

## Question 3

Convert the NumPy array into a Pandas DataFrame.

Column Name: **Salary**

In [ ]:
# Write your code here
df  = pd.DataFrame(arr,columns=['Salary'])
df

   Salary
0   50000
1   42000
2   65000
3   58000
4   45000

## Question 4

Create the Employee DataFrame using the given dataset.

Expected Output: Employee DataFrame

In [ ]:
# Write your code here
df = pd.DataFrame({
    "EmpID":[101,102,103,104,105],
    "Name":["Raj","Amit","Neha","Priya","Rohan"],
    "Department":["IT","HR","IT","Finance","HR"],
    "Salary":[50000,42000,65000,58000,45000],
    "Age":[24,28,26,30,25]
})

df

   EmpID   Name Department  Salary  Age
0    101    Raj         IT   50000   24
1    102   Amit         HR   42000   28
2    103   Neha         IT   65000   26
3    104  Priya    Finance   58000   30
4    105  Rohan         HR   45000   25

## Question 5

Display only the **Name** and **Salary** columns.

Expected Output:

| Name | Salary |
|------|-------:|
|Raj|50000|
|Amit|42000|
|Neha|65000|
|Priya|58000|
|Rohan|45000|

In [ ]:
# Write your code here
(df[['Name','Salary']])

    Name  Salary
0    Raj   50000
1   Amit   42000
2   Neha   65000
3  Priya   58000
4  Rohan   45000

## Question 6

Using **iloc**, display the complete details of the **third employee**.

Expected Output:
```
EmpID 103
Name Neha
Department IT
Salary 65000
Age 26
```

In [ ]:
# Write your code here
print(df.iloc[2])

EmpID           103
Name           Neha
Department       IT
Salary        65000
Age              26
Name: 2, dtype: object

## Question 7

Using **loc**, display only **Raj's Salary**.

Output:
```
50000
```

In [ ]:
# Write your code here
print(df.loc[0,'Salary'])

50000

## Question 8

Display all employees whose Salary is greater than **50000**.

Expected Output:

| Name | Salary |
|------|-------:|
|Neha|65000|
|Priya|58000|

In [ ]:
# Write your code here
print(df[df['Salary']>50000])

   EmpID   Name Department  Salary  Age
2    103   Neha         IT   65000   26
3    104  Priya    Finance   58000   30

## Question 9

Create a new column named **Bonus**.

Formula:
```
Bonus = Salary * 0.10
```

Expected Output:

| Name | Salary | Bonus |
|------|-------:|------:|
|Raj|50000|5000|
|Amit|42000|4200|
|Neha|65000|6500|
|Priya|58000|5800|
|Rohan|45000|4500|

In [ ]:
# Write your code here
df['Bonus'] = df['Salary']*0.10
df

   EmpID   Name Department  Salary  Age   Bonus
0    101    Raj         IT   50000   24  5000.0
1    102   Amit         HR   42000   28  4200.0
2    103   Neha         IT   65000   26  6500.0
3    104  Priya    Finance   58000   30  5800.0
4    105  Rohan         HR   45000   25  4500.0

## Question 10

Update Amit's Salary from **42000** to **48000**.

Expected Output:
Amit -> 48000

In [ ]:
# Write your code here
df.loc[1,'Salary'] = 48000
df

   EmpID   Name Department  Salary  Age   Bonus
0    101    Raj         IT   50000   24  5000.0
1    102   Amit         HR   48000   28  4200.0
2    103   Neha         IT   65000   26  6500.0
3    104  Priya    Finance   58000   30  5800.0
4    105  Rohan         HR   45000   25  4500.0

## Question 11

Replace **HR** with **Human Resource** in the Department column.

Expected Output:
Amit -> Human Resource
Rohan -> Human Resource

In [ ]:
# Write your code here
df['Department'] = df["Department"].replace('HR','Human Resource')
df

   EmpID   Name      Department  Salary  Age   Bonus
0    101    Raj              IT   50000   24  5000.0
1    102   Amit  Human Resource   48000   28  4200.0
2    103   Neha              IT   65000   26  6500.0
3    104  Priya         Finance   58000   30  5800.0
4    105  Rohan  Human Resource   45000   25  4500.0

## Question 12

Sort the DataFrame according to Salary in **Descending Order**.

Expected Order:
Neha
Priya
Raj
Rohan
Amit

In [ ]:
# Write your code here
df = df.sort_values(by='Salary',ascending=False)
df

   EmpID   Name      Department  Salary  Age   Bonus
2    103   Neha              IT   65000   26  6500.0
3    104  Priya         Finance   58000   30  5800.0
0    101    Raj              IT   50000   24  5000.0
1    102   Amit  Human Resource   48000   28  4200.0
4    105  Rohan  Human Resource   45000   25  4500.0

## Question 13

Find the **Average Salary** of each Department using **groupby()**.

Expected Output:
Finance -> 58000
HR -> 43500
IT -> 57500

In [ ]:
# Write your code here
avg_salary = df.groupby('Department')['Salary'].mean()
avg_salary

Department
Finance           58000.0
Human Resource    46500.0
IT                57500.0
Name: Salary, dtype: float64

## Question 14

Set **EmpID** as the index of the DataFrame and display the updated DataFrame.

In [ ]:
# Write your code here
# df = df.set_index('EmpID')
# df

        Name      Department  Salary  Age   Bonus
EmpID
103     Neha              IT   65000   26  6500.0
104    Priya         Finance   58000   30  5800.0
101      Raj              IT   50000   24  5000.0
102     Amit  Human Resource   48000   28  4200.0
105    Rohan  Human Resource   45000   25  4500.0

## Question 15

Create another DataFrame containing **EmpID** and **Experience** and merge it with the Employee DataFrame.

Second DataFrame:

| EmpID | Experience |
|------:|-----------:|
|101|2|
|102|5|
|103|3|
|104|6|
|105|4|

Expected Output: Final merged DataFrame with Experience column.

In [ ]:
# Write your code here
df = pd.DataFrame({
    "EmpID":[101,102,103,104,105],
    "Name":["Raj","Amit","Neha","Priya","Rohan"],
    "Department":["IT","HR","IT","Finance","HR"],
    "Salary":[50000,42000,65000,58000,45000],
    "Age":[24,28,26,30,25]
})
df2 = pd.DataFrame({
    "EmpID":[101,102,103,104,105],
    "Experience":[2,5,3,6,4]
})
final_dataframe = pd.merge(df,df2,on='EmpID')
final_dataframe

   EmpID   Name Department  Salary  Age  Experience
0    101    Raj         IT   50000   24           2
1    102   Amit         HR   42000   28           5
2    103   Neha         IT   65000   26           3
3    104  Priya    Finance   58000   30           6
4    105  Rohan         HR   45000   25           4