<a href="https://colab.research.google.com/github/Ritik-code10/pandas-/blob/main/Pandas_class7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [ ]:
import pandas as pd
# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID" : [101,102,103],
    "ProductName" : ['Pen','Notebook','Marker'],
    "Price" : [10,50,30]
})

# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    'ProductID': [104, 105],
    'ProductName': ['Pencil', 'Eraser'],
    'Price': [5,4]
})
# Dataset 3: Additional info (different columns → good for horizontal stacking)
df3 = pd.DataFrame({
    'Stock': [100, 60, 80],
    'Rating': [4.5,4.7,4.8]
})

print(f'DF1 {df1}')
print(f'DF2 {df2}')
print(f'DF3 {df3}')


#1. Vertical Stacking -> By Default verical stacking in rows wies (axis=0)
vertical_stacking = pd.concat([df1,df2],ignore_index=True)
vertical_stacking

#2.Horizontal Stacking (axis=1)
horizontal_stacking = pd.concat([df1,df3],axis=1)
horizontal_stacking

DF1    ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
DF2    ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser      4
DF3    Stock  Rating
0    100     4.5
1     60     4.7
2     80     4.8

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [ ]:
# You guys have to concat df1 and df2 row wise
product = pd.concat([df1,df2],ignore_index=True)
product

sales = pd.DataFrame({
    "ProductID" : [101,102,104,106],
    "UnitsSold" : [500,200,150,50]
})
print(product)
print(sales)


#1. Inner join (Dono DataFrames ke beech only matching productID)
#          left   right
inner = pd.merge(product,sales,how='inner')
inner

#2. left join
left = pd.merge(product,sales,how='left')
left

#3. Right join

right = pd.merge(product,sales,how='right')
right

#4. Outer join (Everything, even unmatched)
outer = pd.merge(product,sales,how='outer')
outer

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      4
   ProductID  UnitsSold
0        101        500
1        102        200
2        104        150
3        106         50

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    4.0        NaN
5        106         NaN    NaN       50.0

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [ ]:
sales = pd.DataFrame({
    "UnitsSold" : [500,200,150,50,350]
},index=[101,102,103,104,105])
print(product)
print(sales)

#1. join stock info to products
p_indexed = product.set_index('ProductID')
joined = p_indexed.join(sales)
joined

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      4
     UnitsSold
101        500
102        200
103        150
104         50
105        350

          ProductName  Price  UnitsSold
ProductID
101               Pen     10        500
102          Notebook     50        200
103            Marker     30        150
104            Pencil      5         50
105            Eraser      4        350

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [8]:
import pandas as pd
# 1. Create three DataFrames: Products, Sales, and Revenue
products = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'ProductName': ['Pen', 'Notebook', 'Marker'],
    'Price': [10, 50, 30]
})

sales = pd.DataFrame({
    'ProductID': [101, 102, 104, 106],
    'UnitsSold': [500, 200, 150, 50]
})

revenue = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'Revenue': [1000, 800, 1200]
})
# 2. Concatenate them vertically and horizontally
# Write your code here
vertical_stacking = pd.concat([products,sales,revenue],ignore_index=True)
vertical_stacking

horizontal_stacking = pd.concat([products,sales,revenue],axis=1)
horizontal_stacking
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here
merge_inner = pd.merge(sales,revenue,how='inner')
merge_inner

merge_left = pd.merge(sales,revenue,how='left')
merge_left

merge_right = pd.merge(sales,revenue,how='right')
merge_right

merge_outer = pd.merge(sales,revenue,how='outer')
merge_outer

# 4. Join Products with Sales based on index or a key
# Write your code here
p_indexed = products.set_index('ProductID')
joined = p_indexed.join(sales)
joined
# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here
joined.isna()
joined.info()
joined.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 101 to 103
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductName  3 non-null      object
 1   Price        3 non-null      int64
 2   ProductID    0 non-null      float64
 3   UnitsSold    0 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 120.0+ bytes

       Price  ProductID  UnitsSold
count    3.0        0.0        0.0
mean    30.0        NaN        NaN
std     20.0        NaN        NaN
min     10.0        NaN        NaN
25%     20.0        NaN        NaN
50%     30.0        NaN        NaN
75%     40.0        NaN        NaN
max     50.0        NaN        NaN

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.