<a href="https://colab.research.google.com/github/Ritik-code10/pandas-/blob/main/Pandas_Class7_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Class 7 Assignment


### Topics Covered
- Creating DataFrame
- Selecting Columns
- Filtering
- Sorting
- groupby()
- value_counts()
- Creating New Columns
- drop_duplicates()
- fillna()

### Instructions
- Create the DataFrame whenever required.
- Solve all questions using Pandas.
- Write your solution in the blank code cell after each question.

# Q1. Create a Student DataFrame

## Problem Statement
Create the following DataFrame using a Python dictionary.

| Name | Age | City | Marks |
|------|----:|------|------:|
| Aman | 21 | Bhopal | 85 |
| Rahul | 22 | Indore | 72 |
| Neha | 20 | Delhi | 91 |
| Priya | 23 | Bhopal | 68 |
| Ravi | 21 | Indore | 95 |

## Sample Input
```python
{
"Name":["Aman","Rahul","Neha","Priya","Ravi"],
"Age":[21,22,20,23,21],
"City":["Bhopal","Indore","Delhi","Bhopal","Indore"],
"Marks":[85,72,91,68,95]
}
```

## Sample Output
```python
Display the complete DataFrame.
```

In [ ]:
# Write your code here
import pandas as pd
df = pd.DataFrame({
"Name":["Aman","Rahul","Neha","Priya","Ravi"],
"Age":[21,22,20,23,21],
"City":["Bhopal","Indore","Delhi","Bhopal","Indore"],
"Marks":[85,72,91,68,95]
})
df

    Name  Age    City  Marks
0   Aman   21  Bhopal     85
1  Rahul   22  Indore     72
2   Neha   20   Delhi     91
3  Priya   23  Bhopal     68
4   Ravi   21  Indore     95

# Q2. Display Selected Columns

## Problem Statement
Using the DataFrame created in Question 1, display only the **Name** and **Marks** columns.

## Sample Input
```python
Use the DataFrame from Q1
```

## Sample Output
```python
Name and Marks columns only.
```

In [ ]:
# Write your code here
print(df[['Name','Marks']])

    Name  Marks
0   Aman     85
1  Rahul     72
2   Neha     91
3  Priya     68
4   Ravi     95

# Q3. Filter Students

## Problem Statement
Display only those students whose **Marks are greater than 75**.

## Sample Input
```python
Use the DataFrame from Q1
```

## Sample Output
```python
Filtered rows.
```

In [ ]:
# Write your code here
print(df[df['Marks'] > 75])

   Name  Age    City  Marks
0  Aman   21  Bhopal     85
2  Neha   20   Delhi     91
4  Ravi   21  Indore     95

# Q4. Sort by Marks

## Problem Statement
Sort the DataFrame by **Marks** in descending order.

## Sample Input
```python
Use the DataFrame from Q1
```

## Sample Output
```python
Sorted DataFrame.
```

In [ ]:
# Write your code here
print(df.sort_values(by='Marks',ascending=False))

    Name  Age    City  Marks
4   Ravi   21  Indore     95
2   Neha   20   Delhi     91
0   Aman   21  Bhopal     85
1  Rahul   22  Indore     72
3  Priya   23  Bhopal     68

# Q5. Average Marks by City

## Problem Statement
Find the average Marks of each City using **groupby()**.

## Sample Input
```python
Use the DataFrame from Q1
```

## Sample Output
```python
Average marks city-wise.
```

In [ ]:
# Write your code here
print(df.groupby('City')['Marks'].mean())

City
Bhopal    76.5
Delhi     91.0
Indore    83.5
Name: Marks, dtype: float64

# Q6. Count Students by City

## Problem Statement
Count the number of students in each City using **value_counts()**.

## Sample Input
```python
Use the DataFrame from Q1
```

## Sample Output
```python
City frequency.
```

In [ ]:
# Write your code here
print(df['City'].value_counts())

City
Bhopal    2
Indore    2
Delhi     1
Name: count, dtype: int64

# Q7. Create Result Column

## Problem Statement
Create a new column named **Result**. If Marks are **40 or more**, store **Pass**, otherwise **Fail**.

## Sample Input
```python
Use the DataFrame from Q1
```

## Sample Output
```python
Updated DataFrame with Result column.
```

In [ ]:
# Write your code here
df['Result'] = df['Marks'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
df

    Name  Age    City  Marks Result
0   Aman   21  Bhopal     85   Pass
1  Rahul   22  Indore     72   Pass
2   Neha   20   Delhi     91   Pass
3  Priya   23  Bhopal     68   Pass
4   Ravi   21  Indore     95   Pass

# Q8. Remove Duplicate Rows

## Problem Statement
Create the following DataFrame:

| Name | Age | City | Marks |
|------|----:|------|------:|
| Aman | 21 | Bhopal | 85 |
| Rahul | 22 | Indore | 72 |
| Aman | 21 | Bhopal | 85 |
| Neha | 20 | Delhi | 91 |

Remove duplicate rows using **drop_duplicates()**.

## Sample Input
```python
Use the table above.
```

## Sample Output
```python
Duplicate rows removed.
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    "NAme" : ['Aman','Rahul','Aman','Neha'],
    "Age" : [21,22,21,20],
    "City" : ['Bhopal','Indore','Bhopal','Delhi'],
    "Marks" : [85,72,85,91]
})
df.drop_duplicates(inplace=True)
df

    NAme  Age    City  Marks
0   Aman   21  Bhopal     85
1  Rahul   22  Indore     72
3   Neha   20   Delhi     91

# Q9. Fill Missing Values

## Problem Statement
Create the following DataFrame:

| Name | Marks |
|------|------:|
| Aman | 85 |
| Rahul | NaN |
| Neha | 91 |
| Priya | NaN |

Fill missing values in the **Marks** column with **0** using **fillna()**.

## Sample Input
```python
Use the table above.
```

## Sample Output
```python
Missing values replaced with 0.
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    "Name" : ['Aman','Rahul','Neha','Priya'],
    "Marks" : [85,None,91,None]
})
df['Marks'].fillna(0,inplace=True)
df

/tmp/ipykernel_15504/3976869863.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(0,inplace=True)

    Name  Marks
0   Aman   85.0
1  Rahul    0.0
2   Neha   91.0
3  Priya    0.0

# Q10. Final Practice

## Problem Statement
Create a DataFrame with the following data:

| Name | City | Marks |
|------|------|------:|
| Aman | Bhopal | 85 |
| Rahul | Indore | 72 |
| Neha | Delhi | 91 |
| Priya | Bhopal | 68 |
| Ravi | Indore | 95 |

Perform all of the following:
1. Display students with Marks > 80.
2. Sort the DataFrame by Marks.
3. Find the average Marks of each City.

## Sample Input
```python
Use the table above.
```

## Sample Output
```python
Required outputs displayed.
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    "Name" : ['Aman','Rahul','Neha','Priya','Ravi'],
    "City" : ['Bhoapl','Indore','Delhi','Bhopal','Indore'],
    "Marks" : [85,72,91,68,95]
})
print(df[df['Marks'] > 80])
print(df.sort_values('Marks'))
print(df.groupby('City')["Marks"].mean())

   Name    City  Marks
0  Aman  Bhoapl     85
2  Neha   Delhi     91
4  Ravi  Indore     95
    Name    City  Marks
3  Priya  Bhopal     68
1  Rahul  Indore     72
0   Aman  Bhoapl     85
2   Neha   Delhi     91
4   Ravi  Indore     95
City
Bhoapl    85.0
Bhopal    68.0
Delhi     91.0
Indore    83.5
Name: Marks, dtype: float64