<a href="https://colab.research.google.com/github/Ritik-code10/pandas-/blob/main/Pandas_class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [ ]:
Avg_Salary = df.groupby('Department')['Salary'].mean() #har department ki average salary kya hai?
count_Emp = df.groupby('Department')['Employee'].count()#Har departement mai kitne log hai

Multi_stats = df.groupby('Department')['Salary'].agg(['mean','min','max'])
print(Multi_stats)

                    mean    min    max
Department
Finance     61000.000000  58000  65000
HR          51000.000000  50000  52000
IT          72333.333333  70000  75000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

#Department wise average age
Avg_Age = df.groupby('Department')['Age'].mean()
print(Avg_Age)

# df.groupby('Department').agg({column:ispe lagana kya hai mean,min,max,count})
Multi_stats = df.groupby('Department').agg({'Salary':['mean','min','max'], 'Age':['max','min']})
print(Multi_stats)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26
Department
Finance    29.333333
HR         28.500000
IT         31.000000
Name: Age, dtype: float64
                  Salary               Age
                    mean    min    max max min
Department
Finance     61000.000000  58000  65000  35  26
HR          51000.000000  50000  52000  29  28
IT          72333.333333  70000  75000  32  30

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
# df.pivot_table(index='konsa column main hai',values='kya chahiye',aggfunc=mean,min,max,count)
df.pivot_table(index='Department',values='Salary',aggfunc='mean')

df.pivot_table(index='Department', values=['Salary','Age'],aggfunc='mean')

#Age  Group-> 21-25,25-30,31-35
df['Age_Group'] = pd.cut(df['Age'],bins=[25,30,35,40],labels=['25-30','31-35','36-40'])


pd.crosstab(df['Department'],df['Age_Group'])

Age_Group   25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26],
    "City": ["New York", "San Francisco", "San Francisco", "Los Angeles", "New York", "Los Angeles", "San Francisco", "Los Angeles"]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)


# 2. Group by Department to get average Salary and max Age
# Write your code here
Avg_Salary = df.groupby('Department')['Salary'].mean()
Max_Age = df.groupby('Department')['Age'].max()
print(Avg_Salary)
print(Max_Age)

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here
Multi_stats = df.groupby('Department').agg({'Salary':'mean', 'Age':'max'})
print(Multi_stats)

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here
df.pivot_table(index='Department',values='Salary',aggfunc='mean')


# 5. Build a crosstab for Department vs City
# Write your code here
pd.crosstab(df['Department'],df['City'])

Original DataFrame:
  Employee Department  Salary  Age           City
0     John         HR   50000   28       New York
1    Sarah         IT   70000   32  San Francisco
2     Mike         IT   72000   30  San Francisco
3     Anna    Finance   65000   27    Los Angeles
4      Tom    Finance   60000   35       New York
5    Laura         HR   52000   29    Los Angeles
6    Steve         IT   75000   31  San Francisco
7     Kate    Finance   58000   26    Los Angeles
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64
Department
Finance    35
HR         29
IT         32
Name: Age, dtype: int64
                  Salary  Age
Department
Finance     61000.000000   35
HR          51000.000000   29
IT          72333.333333   32

City        Los Angeles  New York  San Francisco
Department
Finance               2         1              0
HR                    1         1              0
IT                    0         0              3

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.